### PR TITLE
Bain's PR

### PR DESCRIPTION
**Pull request by bgdsh**
Hi there,
This is my work on `test-fullstack`.
Some of the code is written in Typescript, if you are not familiar with it, please prepend you are reading pure ES6+ code.

Thanks for reviewing.
Bain

### CODE REVIEW

**Comment by makara** [comment]
OK @bgdsh if you are pushing some tech stack you are gonna try harder, as in Wiredcraft we listen to people when there's the **good reason**. So can you explain your stack such as:

- Why typescript, why do you think our company should use it
- What framework are you using and why, and why not Loopback
- What are the main features have you done
- What advanced challenges have you done and what are your solutions, and why

**Comment by bgdsh** [comment]
@makara 
## Why typescript, why do you think our company should use it

* Typescript is a trend in Javascript ecosystem. Almost every popular `npm` provides their own type definition file. Some of the upgraded version of existing framework chose to use TS, for example Loopback, AntDesign. Vue.js provides their official TS support recently.
* I do not think WiredCraft should ask everyone use it, just need to open this as an opportunity. TS is not suitable for every project, especially very small one. But for the project whose business logic is very complex, TS's pre-build validation can help to prevent a lot of potential bugs.
* TS should not be over used. At least, the code written in TS should be easily read by the developers who are familiar with ES6+. If not, TS will become Java, a very heavy platform.

## Q2: What framework are you using and why, and why not Loopback
* Seneca.js is used for the core service.
* Nest.js is used for the Restful API and WebSocket service.
* Why Nest.js rather than Loopback: 
LoopbackNext is under develop now, it not very stable.
For Loopback 3-, maybe it is the best choice for enterprise development. 
The reason why not use Loopback in this project is I want to show you Nest.js is really a good micro-service framework. I think it can be used as the replacement of Seneca.js. Seneca.js is under bad maintain.

## Q3: What are the main features have you done

* User can register.
* User can login
* User can upvote a talk
* User can post a new talk.
* Page content will be reload once data changed. via WebSocket.
* Use passport-jwt as the auth strategy.
* Use Seneca to implement the core service. Use amqp transporter communicate between gateway and core service.
* Use ELK stack to collect logs. 

## Q4: What advanced challenges have you done and what are your solutions, and why

* The most advanced challenges are learning Mobx.js and Seneca.js for this project. It is the first time I use these 2 technologies in project.
* The real advanced challenge is try to provide the foundational code for a TS full-stack solution. I read a lot of documents to do the tradeoff. I think currently it is good enough. I will improve it continuously.

**Comment by bgdsh** [comment]
Hi there,
Any update?

**Comment by makara** [comment]
Hi @bgdsh,

Sorry for letting you wait. We are not using Typescript at Wiredcraft and was having a hard time to review. We are closing the recruitment before CNY; we'll see if we can come to a conclusion afterward but I'll have to close it for now. Please understand. Meanwhile, if you want to speed it up please try to submit another one with ES.

**Comment by bgdsh** [comment]
Hi @makara , sorry for the inconvenience. Please omit the "Types" in my code. The rest of the code is plain ES. 
Looking forward to join your team.😁

**Pull request closed without merging**
