### PR TITLE
Please review, thank you.

### PR DESCRIPTION
**Pull request by hyifeng**
Hi,

It took me 3 days to complete these works. 
But it still has some significant differences comparing to the requirements.

Please check:
https://github.com/hyifeng/test-fullstack/blob/fb383ceecb7ca6ab74958a8a775dc9248f7c0ef9/README-dev.md

* I use Angular instead of React, because I have no experience on React at the moment.
* I use Bootstrap instead of raw CSS.
* I haven't done the unit test yet. 

I have written a lots of code, can I just pick one or two components to show the unit test or rewrite CSS?

Please let me know your thoughts.

Thank you.

### CODE REVIEW

**Comment by flyingant** [comment]
@hyifeng 
Maybe you could try React for the frontend which is a requirement to the test and the tech stack of our team is based on it.

Our purpose of the test does not actually make it work perfectly but see what's your capabilities.

(Feel free to build the front end by React, we will continue reviewing your code by the way) 💯

**Comment by hyifeng** [comment]
@flyingant 
Thank you for your response.

> Feel free to build the front end by React, we will continue reviewing your code by the way

I see, I can learn React after that, it is on my study list. :+1: 

I think the pull request can explain something, like my programming skills, design abilities, and my attitude whether to take task seriously... etc.

I hope to know that after the review, you can tell me whether I meet your expectations, and feel free to tell me what to do next if you still have concerns.

Thank you.

**Comment by makara** [comment]
Hey @hyifeng, Thank you for the PR.

I'm sure this demonstrates your ability, however, like @flyingant said, Angular is not our tech stack and we are not capable of reviewing it, plus, it doesn't meet the requirement and won't be fair. We also understand you'll need some time to learn about React. Don't worry; we don't have to rush, and quality is not the single criterion here.

Please let us know if you want to redo this with React. Thanks.

**Comment by hyifeng** [comment]
@makara 

> Please let us know if you want to redo this with React.

Yes, I can try.  But it will not be fast.
Close this pull request for now, and submit again later.

Thank you.

**Pull request closed without merging**
